name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Ionos Project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1.0.0
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 07f60c3b-eb34-47c1-8a08-10388d3cb371
          service-host: api-eu.ionos.space
      - name: Deploy to IONOS
        uses: ionos-deploy-now/deploy-to-ionos-action@v1.0.0
        with:
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: ./
          project: 07f60c3b-eb34-47c1-8a08-10388d3cb371
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
